name: "NetSuite guMCP Server"
icon: "assets/icon.png"
description: "Interact with NetSuite data and execute operations including record management, vendor search, and SuiteQL queries"
documentation_path: "README.md"
tools:
  - name: "create_record"
    description: "Creates a new record in NetSuite with the specified record type and data"
  - name: "update_record"
    description: "Updates an existing record in NetSuite with the specified record type, ID, and data"
  - name: "search_vendor_by_email"
    description: "Searches for a vendor in NetSuite by email address"
  - name: "search_vendor_by_name"
    description: "Searches for a vendor in NetSuite by vendor name"
  - name: "execute_suiteql"
    description: "Executes a SuiteQL query string against the NetSuite database"
