name: "Klaviyo guMCP Server"
icon: "assets/icon.png"
description: "Interact with Klaviyo for email marketing, customer engagement, and audience management"
documentation_path: "README.md"
tools:
  # PROFILE MANAGEMENT TOOLS
  - name: "create_profile"
    description: "Creates a new profile with the specified attributes in Klaviyo."
  - name: "get_profile"
    description: "Retrieves a specific profile by its ID from the Klaviyo account."
  - name: "get_profiles"
    description: "Retrieves all profiles from the Klaviyo account."
  - name: "update_profile"
    description: "Updates an existing profile with the given profile ID."
  # CAMPAIGN MANAGEMENT TOOLS
  - name: "get_campaign"
    description: "Retrieves a specific campaign by its ID from the Klaviyo account."
  - name: "list_campaigns"
    description: "Returns campaigns based on the selected channel filter."
  - name: "update_campaign"
    description: "Updates an existing campaign with the given campaign ID."
  - name: "send_campaign"
    description: "Triggers a campaign to send asynchronously."
  - name: "delete_campaign"
    description: "Deletes a campaign with the given campaign ID."
  # LIST MANAGEMENT TOOLS
  - name: "create_list"
    description: "Creates a new list in Klaviyo."
  - name: "get_list"
    description: "Gets a specific list by its ID."
  - name: "get_lists"
    description: "Retrieves all lists from the Klaviyo account."
  - name: "get_list_profiles"
    description: "Gets all profiles within a list with the given list ID."
  - name: "add_profiles_to_list"
    description: "Adds profiles to a list with the given list ID."
  - name: "remove_profiles_from_list"
    description: "Removes profiles from a list with the given list ID."
  # ANALYTICS TOOLS
  - name: "list_metrics"
    description: "Gets all metrics in a Klaviyo account with filtering options."
  - name: "get_metric"
    description: "Gets a specific metric by its ID."
