name: "Monday.com guMCP Server"
icon: "assets/icon.png"
description: "Interact with Monday.com boards, items, groups, and columns using the Monday.com API"
documentation_path: "README.md"
tools:
  - name: "get_me"
    description: "Get the current user's information including name and email"
  - name: "get_boards"
    description: "Get all boards accessible to the user"
  - name: "get_board"
    description: "Get a specific board by ID"
  - name: "get_workspaces"
    description: "Get all workspaces accessible to the user"
  - name: "create_board"
    description: "Create a new board within a workspace"
  - name: "create_item"
    description: "Create a new item in a board"
  - name: "get_group"
    description: "Get a specific group within a board"
  - name: "get_item"
    description: "Get a specific item by its ID"
  - name: "delete_item"
    description: "Delete a specific item by its ID"
  - name: "delete_group"
    description: "Delete a specific group from a board"
  - name: "change_column_value"
    description: "Change the value of a column for a specific item"
  - name: "create_column"
    description: "Create a new column in a board"
  - name: "create_group"
    description: "Create a new group in a board"
  - name: "create_subitem"
    description: "Create a new sub-item under a parent item"
  - name: "delete_subitem"
    description: "Delete a sub-item by its ID"
  - name: "get_subitems"
    description: "Get all subitems of a specific item"
  - name: "archive_item"
    description: "Archive a specific item by its ID"
  - name: "archive_group"
    description: "Archive a specific group in a board"
  - name: "archive_board"
    description: "Archive a specific board by its ID"
