name: "Outlook guMCP Server"
icon: "assets/icon.png"
description: "Read and send emails through Microsoft Outlook"
documentation_path: "README.md"
tools:
  - name: "read_emails"
    description: "Read emails from Outlook. Fetches emails based on specified filters."
  - name: "send_email"
    description: "Send an email using Outlook"
  - name: "move_email"
    description: "Move an email to a different folder like inbox, sentitems, drafts using Outlook"
  - name: "forward_email"
    description: "Forward an email using Outlook"
