name: "PayPal guMCP Server"
icon: "assets/icon.png"
description: "Interact with PayPal payments, orders, and plans management using the PayPal API"
documentation_path: "README.md"
tools:
  - name: "create_order"
    description: "Create a new PayPal order with specified purchase units and intent (CAPTURE or AUTHORIZE)"
  - name: "get_order"
    description: "Get details for a specific PayPal order with optional field filtering"
  - name: "confirm_order"
    description: "Confirm a PayPal order with payment source and optional application context"
  - name: "create_plan"
    description: "Create a new billing plan for subscriptions with product ID, name, description, billing cycles, and payment preferences"
  - name: "list_plans"
    description: "List available billing plans with optional product ID filtering and pagination"
  - name: "get_plan"
    description: "Get detailed information for a specific billing plan"
  - name: "update_plan"
    description: "Update a billing plan's properties using JSON patch operations"
  - name: "activate_plan"
    description: "Activate a billing plan"
  - name: "deactivate_plan"
    description: "Deactivate a billing plan"
  - name: "create_product"
    description: "Create a new product in PayPal catalog with name, description, type (PHYSICAL/DIGITAL/SERVICE), and optional metadata"
  - name: "list_products"
    description: "List available products with pagination support"
  - name: "get_product"
    description: "Get detailed information for a specific product"
  - name: "update_product"
    description: "Update a product's properties using JSON patch operations"
  - name: "search_invoices"
    description: "Search for invoices based on various criteria including recipient info, invoice details, date ranges, and status"
  - name: "create_subscription"
    description: "Create a new subscription with plan ID, optional quantity, auto-renewal, custom ID, and subscriber details"
  - name: "get_subscription"
    description: "Get detailed information for a specific subscription including billing info, status, and subscriber details"
