name: "MailerLite guMCP Server"
icon: "assets/icon.png"
description: "Interact with MailerLite for email marketing automation, including subscriber management, campaign creation, and webhook integration."
documentation_path: "README.md"
tools:
  # Subscriber Management
  - name: "list_all_subscribers"
    description: "List all subscribers in the MailerLite account with optional filtering and pagination."
  - name: "create_subscriber"
    description: "Create a new subscriber with email and optional custom fields."
  - name: "update_subscriber"
    description: "Update an existing subscriber's information and custom fields."
  - name: "get_subscriber"
    description: "Get detailed information about a specific subscriber."
  - name: "delete_subscriber"
    description: "Delete a subscriber from the MailerLite account."
  # Group Management
  - name: "list_groups"
    description: "List all groups in the MailerLite account with optional filtering and sorting."
  - name: "create_group"
    description: "Create a new group for organizing subscribers."
  - name: "update_group"
    description: "Update an existing group's name."
  - name: "delete_group"
    description: "Delete a group from the MailerLite account."
  - name: "get_group_subscribers"
    description: "Get subscribers belonging to a specific group."
  - name: "assign_subscriber_to_group"
    description: "Assign a subscriber to a specific group."
  - name: "unassign_subscriber_from_group"
    description: "Remove a subscriber from a specific group."
  # Field Management
  - name: "list_fields"
    description: "List all custom fields in the MailerLite account."
  - name: "create_field"
    description: "Create a new custom field for subscribers."
  - name: "update_field"
    description: "Update an existing custom field's properties."
  - name: "delete_field"
    description: "Delete a custom field from the MailerLite account."
  # Campaign Management
  - name: "list_campaigns"
    description: "List all campaigns with optional filtering by status and type."
  - name: "get_campaign"
    description: "Get detailed information about a specific campaign."
  - name: "create_campaign"
    description: "Create a new email campaign with content and settings."
  - name: "update_campaign"
    description: "Update an existing campaign's content and settings."
  - name: "schedule_campaign"
    description: "Schedule a campaign for delivery at a specific date and time."
  - name: "cancel_campaign"
    description: "Cancel a scheduled campaign."
  - name: "delete_campaign"
    description: "Delete a campaign from the MailerLite account."
  - name: "list_campaign_languages"
    description: "Get a list of available languages for campaigns."
  # Form Management
  - name: "list_forms"
    description: "List all forms with optional filtering by type and name."
  - name: "get_form"
    description: "Get detailed information about a specific form."
  - name: "update_form"
    description: "Update an existing form's properties."
  - name: "delete_form"
    description: "Delete a form from the MailerLite account."
  # Webhook Management
  - name: "list_webhooks"
    description: "List all webhooks configured in the MailerLite account."
  - name: "get_webhook"
    description: "Get detailed information about a specific webhook."
  - name: "create_webhook"
    description: "Create a new webhook for event notifications."
  - name: "update_webhook"
    description: "Update an existing webhook's configuration."
  - name: "delete_webhook"
    description: "Delete a webhook from the MailerLite account."
