# This is a basic workflow to help you get started with Actions

name: Cloud functions deploy

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [production]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_cloud_function:
    name: Deploy Cloud Function
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false

      - name: Add secrets to env
        run: |
          echo "ANTHROPIC_API_KEY: ${{ secrets.PROD_ANTHROPIC_API_KEY }}" >> .envprod.yaml
          echo "NANGO_SECRET_KEY: ${{ secrets.PROD_NANGO_SECRET_KEY }}" >> .envprod.yaml
          echo 'PEAKFLO_API_BASE_URL: "https://prod-api.peakflo.co/v1"' >> .envprod.yaml

      - name: GCP Auth
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{ secrets.PROD_GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.PROD_GCP_PROJECT_ID }}

      - name: Deploy to GCP
        run: |
          gcloud run deploy pf-mcp --source . --env-vars-file .envprod.yaml --region=us-central1 --no-allow-unauthenticated
